### ISSUE TITLE
Replace the types public API with the Field public API

### ISSUE THREAD

**Issue by pwalsh** [theodi/jsontableschema.rb#9]
In the reference implementation we moved from exposing types to exposing a [Field API](https://github.com/frictionlessdata/jsontableschema-py/blob/master/jsontableschema/field.py#L13). This was happening at the same time as the ruby port, so understandably is not here.

Also I think the change from `convert_*` to `cast_*` semantics occurred at around the same time. [Example](https://github.com/frictionlessdata/jsontableschema-py/blob/master/jsontableschema/field.py#L44).

it would be good to move the Ruby lib to the Field API.

```
# fields (new)
Field({'type': 'number'}).cast_value()

# types (old)
types.NumberType({'type': 'number'}).convert_value()
```

cc @roll

**Comment by roll** [comment]
This API also allows to return to user `Field` instance from `Schema`:

```python
schema = Schema('descriptor.json')
field = schema.get_field('name')
field.name
field.cast_value('value)
```

It's more useful to the user than just a dict. You could see it on the stack reference - https://github.com/frictionlessdata/project/issues/289 (also there are some discrepancies - no descriptor in rb etc - because both works was in parallel)

**Comment by roll** [comment]
> @roll The schema and field connections are defined in https://github.com/theodi/jsontableschema.rb/blob/feature-add-field/lib/jsontableschema/model.rb - which is a Ruby module which is included in schema.rb - I've split a lot of things out into modules, which keeps things neater.

@pezholio 
So when we iterate over `schema.fields` we get Fields instances. Correct? The same for `schema.get_field() -> Field` etc?

**Comment by pezholio** [comment]
That's right 👍

**Comment by roll** [comment]
Thanks! Also starting to understand Ruby a little bit (found `load_fields!`=)
:+1:

**Comment by pezholio** [comment]
Yeah, it wasn't in the most sensible place before. Makes much more sense to have it in `Model`
